### ISSUE TITLE
Add some Animations and UI changes to maintain the smoothness into the website

### ISSUE THREAD

**Issue by Smitkhobragade** [Maddy57770/Fashion-Blog-Template#14]
Pls assign me this issue

**Comment by Maddy57770** [comment]
Sure @Smitkhobragade the issue has been assigned to you. You can improvise the website according your imaginary.

**Comment by Smitkhobragade** [comment]
@Maddy57770 I have Raised The PR . Please Merge it

**Comment by Maddy57770** [comment]
Your PR has successfully been merged. You might checkout the reflected changes on the site.
